"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { CheckCircle2, Clock3, UserRound, XCircle } from "lucide-react";
import { api, getList, getSession } from "@/lib/api";
import type { Broadcast, BroadcastParticipant, User } from "@/lib/types";
import { showToast } from "./toast";
import { Button, Card } from "./ui";

function participantName(participant: BroadcastParticipant) { const user = participant.userId; return typeof user === "string" ? "Community member" : `${user.firstName} ${user.lastName}`; }
function statusIcon(status: BroadcastParticipant["status"]) { return status === "ACCEPTED" ? <CheckCircle2 className="size-4 text-success" /> : status === "PASSED" ? <XCircle className="size-4 text-danger" /> : <Clock3 className="size-4 text-warning" />; }

export function BroadcastDetailWorkspace() {
    const { id } = useParams<{ id: string }>();
    const [broadcast, setBroadcast] = useState<Broadcast | null>(null);
    const [participants, setParticipants] = useState<BroadcastParticipant[]>([]);
    const [error, setError] = useState("");
    const [closing, setClosing] = useState(false);
    const [responding, setResponding] = useState(false);
    useEffect(() => { Promise.all([api<Broadcast>(`/broadcasts/${id}`), getList<BroadcastParticipant>(`/broadcasts/${id}/participants?limit=100`)]).then(([broadcastResult, participantResult]) => { setBroadcast(broadcastResult); setParticipants(participantResult.data); }).catch((reason: Error) => setError(reason.message)); }, [id]);
    async function close() { setClosing(true); try { const closed = await api<Broadcast>(`/broadcasts/${id}/close`, { method: "PATCH" }); setBroadcast(closed); setParticipants((current) => current.map((participant) => participant.status === "PENDING" ? { ...participant, status: "EXPIRED" } : participant)); showToast("Broadcast closed and pending invitations expired.", "success"); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not close broadcast."); } finally { setClosing(false); } }
    async function respond(response: "accept" | "pass") { setResponding(true); try { const result = await api<{ participantCount?: number }>(`/broadcasts/${id}/${response}`, { method: "PATCH" }); setBroadcast((current) => current ? { ...current, participantCount: response === "accept" && typeof result.participantCount === "number" ? result.participantCount : current.participantCount } : current); setParticipants((current) => current.map((participant) => participant.userId === currentUserId || (typeof participant.userId !== "string" && participant.userId._id === currentUserId) ? { ...participant, status: response === "accept" ? "ACCEPTED" : "PASSED" } : participant)); showToast(response === "accept" ? "Broadcast accepted. You can now coordinate in chat." : "Invitation declined.", "success"); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not update this invitation."); } finally { setResponding(false); } }
    if (!broadcast) return <div className="h-72 animate-pulse bg-surface-muted" />;
    const currentUserId = getSession()?.user?._id;
    const isOwner = typeof broadcast.creatorId === "string" ? broadcast.creatorId === currentUserId : (broadcast.creatorId as User | undefined)?._id === currentUserId;
    const currentParticipant = participants.find((participant) => participant.userId === currentUserId || (typeof participant.userId !== "string" && participant.userId._id === currentUserId));
    const canRespond = !isOwner && currentParticipant?.status === "PENDING" && broadcast.status === "ACTIVE";
    const counts = participants.reduce<Record<string, number>>((result, participant) => ({ ...result, [participant.status]: (result[participant.status] ?? 0) + 1 }), {});
    return <div className="grid max-w-4xl gap-6"><Card className="p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wide text-accent">Broadcast detail</p><h2 className="mt-2 text-2xl font-bold text-ink">{broadcast.title ?? "Untitled broadcast"}</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-ink-muted">{broadcast.message}</p></div><span className="rounded-full border border-border bg-surface-muted px-3 py-1 text-xs font-semibold text-ink-muted">{broadcast.status}</span></div><div className="mt-6 flex flex-wrap gap-6 border-t border-border pt-4 text-sm text-ink-muted"><span>{broadcast.participantCount} of {broadcast.maxParticipants} accepted</span><span>{broadcast.postalCode}, {broadcast.state}</span>{isOwner && broadcast.status !== "EXPIRED" && <Button loading={closing} onClick={close} className="ml-auto bg-danger hover:bg-danger">Close broadcast</Button>}</div>{canRespond && <div className="mt-5 flex gap-3"><Button loading={responding} onClick={() => void respond("accept")}>Accept invitation</Button><button type="button" disabled={responding} onClick={() => void respond("pass")} className="h-11 rounded-md border border-border px-4 text-sm font-semibold text-ink-muted hover:border-danger hover:text-danger disabled:opacity-60">Decline</button></div>}{!isOwner && currentParticipant && !canRespond && <p className="mt-5 text-sm font-semibold text-ink-muted">Your invitation status: {currentParticipant.status}</p>}</Card>{isOwner && <Card className="p-6"><div className="flex items-center justify-between"><div><h3 className="font-semibold text-ink">Participants</h3><p className="mt-1 text-sm text-ink-muted">Accepted, pending, and declined invitations.</p></div><span className="text-sm text-ink-muted">{counts.ACCEPTED ?? 0} accepted · {counts.PENDING ?? 0} pending · {counts.PASSED ?? 0} declined</span></div><div className="mt-5 divide-y divide-border">{participants.map((participant) => <div key={participant._id} className="flex items-center justify-between gap-4 py-3"><span className="flex items-center gap-3"><span className="grid size-8 place-items-center rounded-full bg-surface-muted text-accent"><UserRound className="size-4" /></span><span className="text-sm font-medium text-ink">{participantName(participant)}</span></span><span className="inline-flex items-center gap-1.5 text-xs font-semibold text-ink-muted">{statusIcon(participant.status)}{participant.status}</span></div>)}</div></Card>}{error && <p role="alert" className="text-sm text-danger">{error}</p>}</div>;
}