"use client";

import Link from "next/link";
import { Bell, CalendarDays, MessageCircle, Plus, Radio } from "lucide-react";
import { useEffect, useState } from "react";
import { getList } from "@/lib/api";
import type { Broadcast, ChatRoom, Notification } from "@/lib/types";
import { EmptyState } from "./ui";

function dateLabel(value: string) { return new Intl.DateTimeFormat("en", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(value)); }

export function Dashboard() {
    const [data, setData] = useState<{ broadcasts: Broadcast[]; chats: ChatRoom[]; notifications: Notification[] } | null>(null);
    useEffect(() => { Promise.all([getList<Broadcast>("/broadcasts/me/received?limit=3"), getList<ChatRoom>("/chat/me/rooms?limit=3"), getList<Notification>("/notifications?limit=3&unreadOnly=true")]).then(([broadcasts, chats, notifications]) => setData({ broadcasts: broadcasts.data, chats: chats.data, notifications: notifications.data })).catch(() => setData({ broadcasts: [], chats: [], notifications: [] })); }, []);
    const loading = data === null;
    return <div className="grid gap-6 xl:grid-cols-[1.3fr_0.7fr]"><section className="grid gap-6"><div className="grid gap-4 sm:grid-cols-3">{[["Invitations", data?.broadcasts.length ?? 0, Radio, "/broadcasts"], ["Unread updates", data?.notifications.length ?? 0, Bell, "/notifications"], ["Open chats", data?.chats.length ?? 0, MessageCircle, "/chat"]].map(([label, value, Icon, href]) => <Link href={href as string} key={label as string} className="border border-border bg-surface p-5 transition-colors hover:border-accent"><div className="flex items-center justify-between text-ink-muted"><span className="text-sm">{label as string}</span><Icon className="size-4" /></div><p className="mt-5 text-3xl font-bold text-ink">{loading ? "-" : value as number}</p></Link>)}</div><section className="border border-border bg-surface"><div className="flex items-center justify-between border-b border-border px-5 py-4"><div><h2 className="font-semibold text-ink">Nearby invitations</h2><p className="mt-0.5 text-sm text-ink-muted">Plans shared with your interests</p></div><Link href="/broadcasts" className="text-sm font-semibold text-accent hover:text-accent-hover">View all</Link></div>{loading ? <div className="h-48 animate-pulse bg-surface-muted" /> : data.broadcasts.length ? <div>{data.broadcasts.map((broadcast) => <div key={broadcast._id} className="flex gap-4 border-b border-border px-5 py-4 last:border-0"><div className="grid size-10 shrink-0 place-items-center bg-accent-subtle text-accent"><CalendarDays className="size-5" /></div><div className="min-w-0"><p className="font-medium text-ink">{broadcast.message}</p><p className="mt-1 text-sm text-ink-muted">{dateLabel(broadcast.eventDate)} · {broadcast.postalCode}</p></div></div>)}</div> : <EmptyState icon={<Radio className="size-5" />} title="Nothing nearby yet">As people in your community make plans, invitations will appear here.</EmptyState>}</section></section><aside className="border border-border bg-surface"><div className="border-b border-border px-5 py-4"><h2 className="font-semibold text-ink">Keep the circle moving</h2></div><div className="grid gap-3 p-5"><Link href="/broadcasts/new" className="flex items-center gap-3 border border-border p-4 text-sm font-semibold text-ink hover:border-accent"><span className="grid size-8 place-items-center bg-accent-subtle text-accent"><Plus className="size-4" /></span>Create a broadcast</Link><Link href="/onboarding/interests" className="flex items-center gap-3 border border-border p-4 text-sm font-semibold text-ink hover:border-accent"><span className="grid size-8 place-items-center bg-accent-subtle text-accent"><Radio className="size-4" /></span>Update your interests</Link></div></aside></div>;
}